run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
